version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.15-focal
    restart: always
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - mariadb-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      character-set-server: utf8mb4
      collation-server: utf8mb4_bin

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    networks:
      - network-zabbix
    links:
      - mariadb
    restart: always
    ports:
      - '10050:10050'
    volumes:
      - /mnt/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: zabbix
     depends_on:
      - mariadb

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    networks:
      - network-zabbix
    links:
      - mariadb
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: zabbix
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - mariadb

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10051:10051'
    environment:
      ZBX_HOSTNAME: zabbix-server
      ZBX_SERVER_HOST: 127.0.0.1
 grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    networks:
      - network-zabbix
    links:
      - mariadb
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      GF_SECURITY_ADMIN_PASSWORD: "123456"
      GF_PLUGINS_ALLOW_LOADING_USIGNED_PLUGINS: alexanderzobnin-zabbix-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mariadb
      - zabbix-server

volumes:
  mariadb-storage:
  grafana-storage:

networks:
  network-zabbix:
    driver: bridge
