version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.36
    restart: always
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      character-set-server: utf8mb4
      collation-server: utf8mb4_bin

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-6.4-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10050:10050'
    volumes:
      - /mnt/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: zabbix
    depends_on:
      - mysql
       zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: zabbix
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - mysql

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      GF_SECURITY_ADMIN_PASSWORD: "123456"
      GF_PLUGINS_ALLOW_LOADING_USIGNED_PLUGINS: alexanderzobnin-zabbix-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mysql
      - zabbix-server

volumes:
  mysql-storage:
  grafana-storage:
