services:
  checkmk:
    image: "checkmk/check-mk-community:latest"
    container_name: "monitoring"
    restart: always
    environment:
      - CMK_PASSWORD=mypassword   # Change this to a secure password
      - TZ=Europe/Berlin          # Adjust to your local timezone
    volumes:
      - monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ports:
      - "8080:5000"   # HTTP Web UI (Host port : Container port)
      - "8000:8000"   # Agent TLS registration port

volumes:
  monitoring:
