version: '3'
services:
  kuma:
    image: louislam/uptime-kuma:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3010:3001/tcp"
      - "3010:3001/udp"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - /mnt/kumauptime:/app/data
