version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      GF_SECURITY_ADMIN_PASSWORD: "123456"
      GF_PLUGINS_ALLOW_LOADING_USIGNED_PLUGINS: alexanderzobnin-zabbix-datasource
    ports:
      - 3000:3000
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

#Subir a aplicação no cluster swarm
#docker stack deploy -c docker-compose.yml (nomedastack)
