version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - visualizer
  kuma:
    image: louislam/uptime-kuma:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3002:3001"
    volumes:
      - kuma-storage:/app/data
    depends_on:
      - visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8888:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  grafana-storage:
  kuma-storage:
