  GNU nano 5.6.1                                            kuma-swarm.yml                                                         version: '3.8'
services:
  kuma:
    image: louislam/uptime-kuma:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 3010:3001
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - /mnt/kumauptime:/app/data

#Subir a aplicação no cluster swarm
#docker stack deploy -c docker-compose.yml (nomedastack)
