version: '3'
services:
  bind9-1:
    container_name: dns-1
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Sao_Paulo
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /mnt/config:/etc/bind
      - /mnt/cache:/var/cache/bind
      - /mnt/records:/var/lib/bind
    restart: unless-stopped
