version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=10.0.0.240 #optional
    volumes:
      - /mnt/jellyfin/library:/config
      - /mnt/jellyfin/tvseries:/data/tvshows
      - /mnt/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
