version: "2.1"
services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      #- PUID=1000 #optional
      #- PGID=1000 #optional
      - TZ=America/Sao_Paulo #optional
      - SUBDOMAINS=armbian,silva,lab-docker
      - TOKEN=5730-6e26-4c1f-9c80-ca7f8876
      - LOG_FILE=false #optional
    volumes:
      - /mnt/duckdns:/config #optional
    restart: always
